name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Change if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: stock-buy-alert  # Ensure this matches the correct GCP project ID

    - name: Configure Docker to use Google Cloud Artifact Registry
      run: |
        gcloud auth configure-docker gcr.io

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/stock-buy-alert/stock-buy-alert

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy stock-buy-alert \
          --image gcr.io/stock-buy-alert/stock-buy-alert \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --service-account github-actions-deploy@stock-buy-alert.iam.gserviceaccount.com
